// stores names for every character in every game ...
// tooltip functionality from http://jsfiddle.net/2vc8y5ox/ and
// https://stackoverflow.com/questions/15702867/html-tooltip-position-relative-to-mouse-pointer !
const allCharacters = [	[],
						["Mars", "Luke"],
						["Mars", "Sheeda", "Jeigan"],
						["Marth", "Kris"],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],
						[],];
